//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataquadEntities : DbContext
    {
        public DataquadEntities()
            : base("name=DataquadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<userLoginDetails> userLoginDetails { get; set; }
        public virtual DbSet<userProfileImages> userProfileImages { get; set; }
        public virtual DbSet<userFilesCollection> userFilesCollections { get; set; }
        public virtual DbSet<userDetails> userDetails { get; set; }
        public virtual DbSet<userPersonalDetails> userPersonalDetails { get; set; }
        public virtual DbSet<Race> Races { get; set; }
    }
}
