//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userDetails()
        {
            this.tbl_userPersonalDetail = new HashSet<userPersonalDetails>();
        }
    
        public int userId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string emailId { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public string password { get; set; }
        public bool isEmailVerified { get; set; }
        public System.Guid activationCode { get; set; }
        public string resetPasswordCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userPersonalDetails> tbl_userPersonalDetail { get; set; }
    }
}
