//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.DataQuadService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="userDetailsModel", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class userDetailsModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid activationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isEmailVerifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resetPasswordCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVC.DataQuadService.tbl_userPersonalDetail[] tbl_userPersonalDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid activationCode {
            get {
                return this.activationCodeField;
            }
            set {
                if ((this.activationCodeField.Equals(value) != true)) {
                    this.activationCodeField = value;
                    this.RaisePropertyChanged("activationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                if ((this.dateOfBirthField.Equals(value) != true)) {
                    this.dateOfBirthField = value;
                    this.RaisePropertyChanged("dateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emailId {
            get {
                return this.emailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.emailIdField, value) != true)) {
                    this.emailIdField = value;
                    this.RaisePropertyChanged("emailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isEmailVerified {
            get {
                return this.isEmailVerifiedField;
            }
            set {
                if ((this.isEmailVerifiedField.Equals(value) != true)) {
                    this.isEmailVerifiedField = value;
                    this.RaisePropertyChanged("isEmailVerified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resetPasswordCode {
            get {
                return this.resetPasswordCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.resetPasswordCodeField, value) != true)) {
                    this.resetPasswordCodeField = value;
                    this.RaisePropertyChanged("resetPasswordCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVC.DataQuadService.tbl_userPersonalDetail[] tbl_userPersonalDetail {
            get {
                return this.tbl_userPersonalDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_userPersonalDetailField, value) != true)) {
                    this.tbl_userPersonalDetailField = value;
                    this.RaisePropertyChanged("tbl_userPersonalDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_userPersonalDetail", Namespace="http://schemas.datacontract.org/2004/07/WCFService.DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class tbl_userPersonalDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EthnicityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TechnologyInterstedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVC.DataQuadService.tbl_userDetails tbl_userDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> userIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ethnicity {
            get {
                return this.EthnicityField;
            }
            set {
                if ((object.ReferenceEquals(this.EthnicityField, value) != true)) {
                    this.EthnicityField = value;
                    this.RaisePropertyChanged("Ethnicity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Race {
            get {
                return this.RaceField;
            }
            set {
                if ((object.ReferenceEquals(this.RaceField, value) != true)) {
                    this.RaceField = value;
                    this.RaisePropertyChanged("Race");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TechnologyIntersted {
            get {
                return this.TechnologyInterstedField;
            }
            set {
                if ((object.ReferenceEquals(this.TechnologyInterstedField, value) != true)) {
                    this.TechnologyInterstedField = value;
                    this.RaisePropertyChanged("TechnologyIntersted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVC.DataQuadService.tbl_userDetails tbl_userDetails {
            get {
                return this.tbl_userDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_userDetailsField, value) != true)) {
                    this.tbl_userDetailsField = value;
                    this.RaisePropertyChanged("tbl_userDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_userDetails", Namespace="http://schemas.datacontract.org/2004/07/WCFService.DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class tbl_userDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid activationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isEmailVerifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resetPasswordCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVC.DataQuadService.tbl_userPersonalDetail[] tbl_userPersonalDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid activationCode {
            get {
                return this.activationCodeField;
            }
            set {
                if ((this.activationCodeField.Equals(value) != true)) {
                    this.activationCodeField = value;
                    this.RaisePropertyChanged("activationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                if ((this.dateOfBirthField.Equals(value) != true)) {
                    this.dateOfBirthField = value;
                    this.RaisePropertyChanged("dateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emailId {
            get {
                return this.emailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.emailIdField, value) != true)) {
                    this.emailIdField = value;
                    this.RaisePropertyChanged("emailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isEmailVerified {
            get {
                return this.isEmailVerifiedField;
            }
            set {
                if ((this.isEmailVerifiedField.Equals(value) != true)) {
                    this.isEmailVerifiedField = value;
                    this.RaisePropertyChanged("isEmailVerified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resetPasswordCode {
            get {
                return this.resetPasswordCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.resetPasswordCodeField, value) != true)) {
                    this.resetPasswordCodeField = value;
                    this.RaisePropertyChanged("resetPasswordCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVC.DataQuadService.tbl_userPersonalDetail[] tbl_userPersonalDetail {
            get {
                return this.tbl_userPersonalDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_userPersonalDetailField, value) != true)) {
                    this.tbl_userPersonalDetailField = value;
                    this.RaisePropertyChanged("tbl_userPersonalDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="userProfileImageModel", Namespace="http://schemas.datacontract.org/2004/07/WCFService.Models")]
    [System.SerializableAttribute()]
    public partial class userProfileImageModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ImageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ImageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ImageData {
            get {
                return this.ImageDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageDataField, value) != true)) {
                    this.ImageDataField = value;
                    this.RaisePropertyChanged("ImageData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImageId {
            get {
                return this.ImageIdField;
            }
            set {
                if ((this.ImageIdField.Equals(value) != true)) {
                    this.ImageIdField = value;
                    this.RaisePropertyChanged("ImageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ImageSize {
            get {
                return this.ImageSizeField;
            }
            set {
                if ((this.ImageSizeField.Equals(value) != true)) {
                    this.ImageSizeField = value;
                    this.RaisePropertyChanged("ImageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_userProfileImages", Namespace="http://schemas.datacontract.org/2004/07/WCFService.DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class tbl_userProfileImages : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Web.HttpPostedFileBase FileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ImageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ImageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVC.DataQuadService.tbl_userLoginDetails tbl_userLoginDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Web.HttpPostedFileBase File {
            get {
                return this.FileField;
            }
            set {
                if ((object.ReferenceEquals(this.FileField, value) != true)) {
                    this.FileField = value;
                    this.RaisePropertyChanged("File");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ImageData {
            get {
                return this.ImageDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageDataField, value) != true)) {
                    this.ImageDataField = value;
                    this.RaisePropertyChanged("ImageData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImageId {
            get {
                return this.ImageIdField;
            }
            set {
                if ((this.ImageIdField.Equals(value) != true)) {
                    this.ImageIdField = value;
                    this.RaisePropertyChanged("ImageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ImageSize {
            get {
                return this.ImageSizeField;
            }
            set {
                if ((this.ImageSizeField.Equals(value) != true)) {
                    this.ImageSizeField = value;
                    this.RaisePropertyChanged("ImageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVC.DataQuadService.tbl_userLoginDetails tbl_userLoginDetails {
            get {
                return this.tbl_userLoginDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_userLoginDetailsField, value) != true)) {
                    this.tbl_userLoginDetailsField = value;
                    this.RaisePropertyChanged("tbl_userLoginDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_userLoginDetails", Namespace="http://schemas.datacontract.org/2004/07/WCFService.DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class tbl_userLoginDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVC.DataQuadService.tbl_userFilesCollection[] tbl_userFilesCollectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVC.DataQuadService.tbl_userProfileImages[] tbl_userProfileImagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVC.DataQuadService.tbl_userFilesCollection[] tbl_userFilesCollection {
            get {
                return this.tbl_userFilesCollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_userFilesCollectionField, value) != true)) {
                    this.tbl_userFilesCollectionField = value;
                    this.RaisePropertyChanged("tbl_userFilesCollection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVC.DataQuadService.tbl_userProfileImages[] tbl_userProfileImages {
            get {
                return this.tbl_userProfileImagesField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_userProfileImagesField, value) != true)) {
                    this.tbl_userProfileImagesField = value;
                    this.RaisePropertyChanged("tbl_userProfileImages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_userFilesCollection", Namespace="http://schemas.datacontract.org/2004/07/WCFService.DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class tbl_userFilesCollection : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FileDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FileIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FileSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVC.DataQuadService.tbl_userLoginDetails tbl_userLoginDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileContentType {
            get {
                return this.FileContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FileContentTypeField, value) != true)) {
                    this.FileContentTypeField = value;
                    this.RaisePropertyChanged("FileContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FileData {
            get {
                return this.FileDataField;
            }
            set {
                if ((object.ReferenceEquals(this.FileDataField, value) != true)) {
                    this.FileDataField = value;
                    this.RaisePropertyChanged("FileData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileExtension {
            get {
                return this.FileExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.FileExtensionField, value) != true)) {
                    this.FileExtensionField = value;
                    this.RaisePropertyChanged("FileExtension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FileId {
            get {
                return this.FileIdField;
            }
            set {
                if ((this.FileIdField.Equals(value) != true)) {
                    this.FileIdField = value;
                    this.RaisePropertyChanged("FileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FileSize {
            get {
                return this.FileSizeField;
            }
            set {
                if ((this.FileSizeField.Equals(value) != true)) {
                    this.FileSizeField = value;
                    this.RaisePropertyChanged("FileSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVC.DataQuadService.tbl_userLoginDetails tbl_userLoginDetails {
            get {
                return this.tbl_userLoginDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_userLoginDetailsField, value) != true)) {
                    this.tbl_userLoginDetailsField = value;
                    this.RaisePropertyChanged("tbl_userLoginDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_race", Namespace="http://schemas.datacontract.org/2004/07/WCFService.DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class tbl_race : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int raceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string raceNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int raceId {
            get {
                return this.raceIdField;
            }
            set {
                if ((this.raceIdField.Equals(value) != true)) {
                    this.raceIdField = value;
                    this.RaisePropertyChanged("raceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string raceName {
            get {
                return this.raceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.raceNameField, value) != true)) {
                    this.raceNameField = value;
                    this.RaisePropertyChanged("raceName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataQuadService.IDataQuadService")]
    public interface IDataQuadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQuadService/GetUserDetailByUserId", ReplyAction="http://tempuri.org/IDataQuadService/GetUserDetailByUserIdResponse")]
        MVC.DataQuadService.userDetailsModel GetUserDetailByUserId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQuadService/GetUserDetailByUserId", ReplyAction="http://tempuri.org/IDataQuadService/GetUserDetailByUserIdResponse")]
        System.Threading.Tasks.Task<MVC.DataQuadService.userDetailsModel> GetUserDetailByUserIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQuadService/sample", ReplyAction="http://tempuri.org/IDataQuadService/sampleResponse")]
        string sample();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQuadService/sample", ReplyAction="http://tempuri.org/IDataQuadService/sampleResponse")]
        System.Threading.Tasks.Task<string> sampleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQuadService/RegisterUser", ReplyAction="http://tempuri.org/IDataQuadService/RegisterUserResponse")]
        bool RegisterUser(MVC.DataQuadService.userDetailsModel user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQuadService/RegisterUser", ReplyAction="http://tempuri.org/IDataQuadService/RegisterUserResponse")]
        System.Threading.Tasks.Task<bool> RegisterUserAsync(MVC.DataQuadService.userDetailsModel user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQuadService/GetProfileImageByUserId", ReplyAction="http://tempuri.org/IDataQuadService/GetProfileImageByUserIdResponse")]
        MVC.DataQuadService.userProfileImageModel GetProfileImageByUserId(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQuadService/GetProfileImageByUserId", ReplyAction="http://tempuri.org/IDataQuadService/GetProfileImageByUserIdResponse")]
        System.Threading.Tasks.Task<MVC.DataQuadService.userProfileImageModel> GetProfileImageByUserIdAsync(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQuadService/SaveProfileImage", ReplyAction="http://tempuri.org/IDataQuadService/SaveProfileImageResponse")]
        void SaveProfileImage(MVC.DataQuadService.tbl_userProfileImages image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQuadService/SaveProfileImage", ReplyAction="http://tempuri.org/IDataQuadService/SaveProfileImageResponse")]
        System.Threading.Tasks.Task SaveProfileImageAsync(MVC.DataQuadService.tbl_userProfileImages image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQuadService/GetPersonalDetailByUserId", ReplyAction="http://tempuri.org/IDataQuadService/GetPersonalDetailByUserIdResponse")]
        MVC.DataQuadService.tbl_userPersonalDetail GetPersonalDetailByUserId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQuadService/GetPersonalDetailByUserId", ReplyAction="http://tempuri.org/IDataQuadService/GetPersonalDetailByUserIdResponse")]
        System.Threading.Tasks.Task<MVC.DataQuadService.tbl_userPersonalDetail> GetPersonalDetailByUserIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQuadService/SavePersonalDetail", ReplyAction="http://tempuri.org/IDataQuadService/SavePersonalDetailResponse")]
        void SavePersonalDetail(MVC.DataQuadService.tbl_userPersonalDetail userPersonalDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQuadService/SavePersonalDetail", ReplyAction="http://tempuri.org/IDataQuadService/SavePersonalDetailResponse")]
        System.Threading.Tasks.Task SavePersonalDetailAsync(MVC.DataQuadService.tbl_userPersonalDetail userPersonalDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQuadService/GetAllRaces", ReplyAction="http://tempuri.org/IDataQuadService/GetAllRacesResponse")]
        MVC.DataQuadService.tbl_race[] GetAllRaces();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQuadService/GetAllRaces", ReplyAction="http://tempuri.org/IDataQuadService/GetAllRacesResponse")]
        System.Threading.Tasks.Task<MVC.DataQuadService.tbl_race[]> GetAllRacesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQuadService/GetAllFilesByUserId", ReplyAction="http://tempuri.org/IDataQuadService/GetAllFilesByUserIdResponse")]
        MVC.DataQuadService.tbl_userFilesCollection[] GetAllFilesByUserId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQuadService/GetAllFilesByUserId", ReplyAction="http://tempuri.org/IDataQuadService/GetAllFilesByUserIdResponse")]
        System.Threading.Tasks.Task<MVC.DataQuadService.tbl_userFilesCollection[]> GetAllFilesByUserIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQuadService/GetFileByFileId", ReplyAction="http://tempuri.org/IDataQuadService/GetFileByFileIdResponse")]
        MVC.DataQuadService.tbl_userFilesCollection GetFileByFileId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQuadService/GetFileByFileId", ReplyAction="http://tempuri.org/IDataQuadService/GetFileByFileIdResponse")]
        System.Threading.Tasks.Task<MVC.DataQuadService.tbl_userFilesCollection> GetFileByFileIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQuadService/SaveFile", ReplyAction="http://tempuri.org/IDataQuadService/SaveFileResponse")]
        void SaveFile(MVC.DataQuadService.tbl_userFilesCollection file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQuadService/SaveFile", ReplyAction="http://tempuri.org/IDataQuadService/SaveFileResponse")]
        System.Threading.Tasks.Task SaveFileAsync(MVC.DataQuadService.tbl_userFilesCollection file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQuadService/DeleteFile", ReplyAction="http://tempuri.org/IDataQuadService/DeleteFileResponse")]
        void DeleteFile(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQuadService/DeleteFile", ReplyAction="http://tempuri.org/IDataQuadService/DeleteFileResponse")]
        System.Threading.Tasks.Task DeleteFileAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataQuadServiceChannel : MVC.DataQuadService.IDataQuadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataQuadServiceClient : System.ServiceModel.ClientBase<MVC.DataQuadService.IDataQuadService>, MVC.DataQuadService.IDataQuadService {
        
        public DataQuadServiceClient() {
        }
        
        public DataQuadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataQuadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataQuadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataQuadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVC.DataQuadService.userDetailsModel GetUserDetailByUserId(int id) {
            return base.Channel.GetUserDetailByUserId(id);
        }
        
        public System.Threading.Tasks.Task<MVC.DataQuadService.userDetailsModel> GetUserDetailByUserIdAsync(int id) {
            return base.Channel.GetUserDetailByUserIdAsync(id);
        }
        
        public string sample() {
            return base.Channel.sample();
        }
        
        public System.Threading.Tasks.Task<string> sampleAsync() {
            return base.Channel.sampleAsync();
        }
        
        public bool RegisterUser(MVC.DataQuadService.userDetailsModel user) {
            return base.Channel.RegisterUser(user);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterUserAsync(MVC.DataQuadService.userDetailsModel user) {
            return base.Channel.RegisterUserAsync(user);
        }
        
        public MVC.DataQuadService.userProfileImageModel GetProfileImageByUserId(System.Nullable<int> id) {
            return base.Channel.GetProfileImageByUserId(id);
        }
        
        public System.Threading.Tasks.Task<MVC.DataQuadService.userProfileImageModel> GetProfileImageByUserIdAsync(System.Nullable<int> id) {
            return base.Channel.GetProfileImageByUserIdAsync(id);
        }
        
        public void SaveProfileImage(MVC.DataQuadService.tbl_userProfileImages image) {
            base.Channel.SaveProfileImage(image);
        }
        
        public System.Threading.Tasks.Task SaveProfileImageAsync(MVC.DataQuadService.tbl_userProfileImages image) {
            return base.Channel.SaveProfileImageAsync(image);
        }
        
        public MVC.DataQuadService.tbl_userPersonalDetail GetPersonalDetailByUserId(int id) {
            return base.Channel.GetPersonalDetailByUserId(id);
        }
        
        public System.Threading.Tasks.Task<MVC.DataQuadService.tbl_userPersonalDetail> GetPersonalDetailByUserIdAsync(int id) {
            return base.Channel.GetPersonalDetailByUserIdAsync(id);
        }
        
        public void SavePersonalDetail(MVC.DataQuadService.tbl_userPersonalDetail userPersonalDetail) {
            base.Channel.SavePersonalDetail(userPersonalDetail);
        }
        
        public System.Threading.Tasks.Task SavePersonalDetailAsync(MVC.DataQuadService.tbl_userPersonalDetail userPersonalDetail) {
            return base.Channel.SavePersonalDetailAsync(userPersonalDetail);
        }
        
        public MVC.DataQuadService.tbl_race[] GetAllRaces() {
            return base.Channel.GetAllRaces();
        }
        
        public System.Threading.Tasks.Task<MVC.DataQuadService.tbl_race[]> GetAllRacesAsync() {
            return base.Channel.GetAllRacesAsync();
        }
        
        public MVC.DataQuadService.tbl_userFilesCollection[] GetAllFilesByUserId(int id) {
            return base.Channel.GetAllFilesByUserId(id);
        }
        
        public System.Threading.Tasks.Task<MVC.DataQuadService.tbl_userFilesCollection[]> GetAllFilesByUserIdAsync(int id) {
            return base.Channel.GetAllFilesByUserIdAsync(id);
        }
        
        public MVC.DataQuadService.tbl_userFilesCollection GetFileByFileId(int id) {
            return base.Channel.GetFileByFileId(id);
        }
        
        public System.Threading.Tasks.Task<MVC.DataQuadService.tbl_userFilesCollection> GetFileByFileIdAsync(int id) {
            return base.Channel.GetFileByFileIdAsync(id);
        }
        
        public void SaveFile(MVC.DataQuadService.tbl_userFilesCollection file) {
            base.Channel.SaveFile(file);
        }
        
        public System.Threading.Tasks.Task SaveFileAsync(MVC.DataQuadService.tbl_userFilesCollection file) {
            return base.Channel.SaveFileAsync(file);
        }
        
        public void DeleteFile(int id) {
            base.Channel.DeleteFile(id);
        }
        
        public System.Threading.Tasks.Task DeleteFileAsync(int id) {
            return base.Channel.DeleteFileAsync(id);
        }
    }
}
